/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:632950:
  appc.background(230);
} //_CODE_:window1:632950:

public void textfield1_change1(GTextField source, GEvent event) { //_CODE_:textfield1:428234:
  //println("textfield1 - GTextField >> GEvent." + event + " @ " + millis());

} //_CODE_:textfield1:428234:

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:469553:
  //println("button1 - GButton >> GEvent." + event + " @ " + millis());

   A = new aes(textfield1.getText());// get text from text box
   A.display = true;//Displays when button is clicked
   for(int i = 0; i < A.encrypt().length(); i++){
     A.ecText +=Integer.toHexString(A.encrypt().charAt(i));//Cipher text
   }
   
} //_CODE_:button1:469553:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 240, 120, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw1");
  label1 = new GLabel(window1, 5, 5, 222, 20);
  label1.setText("Enter CipherText (Max 16 Characters)");
  label1.setOpaque(false);
  textfield1 = new GTextField(window1, 5, 25, 175, 75, G4P.SCROLLBARS_NONE);
  textfield1.setOpaque(true);
  textfield1.addEventHandler(this, "textfield1_change1");
  button1 = new GButton(window1, 190, 25, 40, 75);
  button1.setText("OK");
  button1.addEventHandler(this, "button1_click1");
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;
GLabel label1; 
GTextField textfield1; 
GButton button1; 
